config/routes.rb
Rails.application.routes.draw do
  controller :store_sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :host_users, except: :new
  controller :host_users do
    get 'signup' => :new
  end
  mount Spree::Core::Engine, :at => '/'

end

app/models/host_user.rb
class HostUser < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/host_users_controller.rb
class HostUsersController < ApplicationController
  before_action :set_host_user, only: [:show, :edit, :update, :destroy]

  # GET /host_users
  # GET /host_users.json
  def index
    @host_users = HostUser.order(:name)
  end

  # GET /host_users/1
  # GET /host_users/1.json
  def show
  end

  # GET /host_users/new
  def new
    @host_user = HostUser.new
  end

  # GET /host_users/1/edit
  def edit
  end

  # POST /host_users
  # POST /host_users.json
  def create
    @host_user = HostUser.new(host_user_params)

    respond_to do |format|
      if @host_user.save
        format.html { redirect_to host_users_url, notice: "User #{@host_user.name} was successfully created." }
        format.json { render :show, status: :created, location: @host_user }
      else
        format.html { render :new }
        format.json { render json: @host_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /host_users/1
  # PATCH/PUT /host_users/1.json
  def update
    respond_to do |format|
      if @host_user.update(host_user_params)
        format.html { redirect_to host_users_url, notice: "User #{@host_user.name} was successfully updated."}
        format.json { render :show, status: :ok, location: @host_user }
      else
        format.html { render :edit }
        format.json { render json: @host_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /host_users/1
  # DELETE /host_users/1.json
  def destroy
    @host_user.destroy
    respond_to do |format|
      format.html { redirect_to host_users_url, notice: 'Host user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host_user
      @host_user = HostUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_user_params
      params.require(:host_user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/store_sessions_controller.rb
class StoreSessionsController < ApplicationController
  def new
  end

  def create
    user = HostUser.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:host_user_id] = user.id
      redirect_to '/'
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:host_user_id] = nil
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host_users_helper.rb
module HostUsersHelper
end

app/helpers/store_sessions_helper.rb
module StoreSessionsHelper
end

app/views/host_users/_form.html.erb
<%= form_for(@host_user) do |f| %>
  <% if @host_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host_user.errors.count, "error") %> prohibited this host_user from being saved:</h2>

      <ul>
      <% @host_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br>
    <%= f.password_field :password, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %><br>
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/host_users/edit.html.erb
<h1>Editing Host User</h1>

<%= render 'form' %>

<%= link_to 'Show', @host_user %> |
<%= link_to 'Back', host_users_path %>

app/views/host_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Host Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @host_users.each do |host_user| %>
      <tr>
        <td><%= host_user.name %></td>
        <td><%= host_user.email %></td>
        <td><%= link_to 'Show', host_user %></td>
        <td><%= link_to 'Edit', edit_host_user_path(host_user) %></td>
        <td><%= link_to 'Destroy', host_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host user', signup_path %>

app/views/host_users/new.html.erb
<h1>New Host User</h1>

<%= render 'form' %>

<%= link_to 'Back', host_users_path %>

app/views/host_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @host_user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @host_user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @host_user.password_digest %>
</p>

<%= link_to 'Edit', edit_host_user_path(@host_user) %> |
<%= link_to 'Back', host_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Touriapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/shared/_login_bar.html.erb
<% if spree_current_user %>
  <li>
    <%= link_to Spree.t(:logout), spree_logout_path, :method => :delete %>
  </li>
<% else %>
  <li>
    <%= link_to Spree.t(:login), spree_login_path %>
  </li>
  <li>
    <%= link_to Spree.t(:signup), spree_signup_path %>
  </li>
<% end %>

app/views/store_sessions/create.html.erb
<h1>StoreSessions#create</h1>
<p>Find me in app/views/store_sessions/create.html.erb</p>

app/views/store_sessions/destroy.html.erb
<h1>StoreSessions#destroy</h1>
<p>Find me in app/views/store_sessions/destroy.html.erb</p>

app/views/store_sessions/new.html.erb
<h1>Login</h1>
<% if flash[:alert] %>
  <p id="notice"><%= flash[:alert] %></p>
<% end %>
  
<%= form_tag do %>
  <div>
    <%= label_tag :email, 'Email:' %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div>
    <%= label_tag :password, 'Password:' %>
    <%= password_field_tag :password, params[:password] %>
  </div>
  <div>
    <%= submit_tag "Login" %>
  </div>
<% end %>